title: "Digital Reader"
email: sarahc@pvep.com
description: The Literacy Tool That Fits Every Classroom
image: 'assets/images/about.png'
timezone: UTC
baseurl: "/digital-reader-blog/"
permalink: "/:title/"
logo: 'assets/images/let-read-square.png'
icon: 'assets/images/digital-reader.svg'
favicon: 'assets/images/favicon.png'
author:
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: 'assets/images/about.png'

# Authors
authors:
  Michèle Dufresne:
    name: Michèle Dufresne
    display_name: Michèle Dufresne
    avatar: 'assets/images/michele.png'
    email: contactus@pioneervalleybooks.com
    web: https://www.digitalreader.com/
    twitter: https://twitter.com/pvalleybooks
    description: "Pioneer Valley Books President Michèle Dufresne needs little introduction as the heart of our company and a founding member. She is a former Reading Recovery Teacher Leader. She started writing books when working with some of her first Reading Recovery students who needed some extra motivation. She is passionate about helping teachers with their mission of helping children learn to read and write and love books."

# Social
social:
  instagram: https://www.instagram.com/pvalleybooks/
  facebook: https://www.facebook.com/pioneervalleybooks
  twitter: https://twitter.com/pvalleybooks
  youtube: https://www.youtube.com/user/pioneervalleybooks

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
