title: "Let's Read!"
email: sarahc@pvep.com
description: The blog site for the Digital Reader
image: 'assets/images/2023-08-22-image-lets-read-blog.png'
timezone: UTC
baseurl: "/digital-reader-blog"
permalink: "/:title/"
logo: 'assets/images/lets-read-dr.png'
icon: 'assets/images/digital-reader.svg'
favicon: 'assets/images/favicon.png'
author:
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: 'assets/images/2023-08-22-image-lets-read-blog.png'

# Authors
authors:
  Michèle Dufresne:
    name: Michèle Dufresne
    display_name: Michèle Dufresne
    avatar: 'assets/images/michele.png'
    email: contactus@pioneervalleybooks.com
    description: "Dr. Michèle Dufresne is an author, education consultant and former Reading Recovery® Teacher Leader. She's a best-selling co-author of <em>The Next Step Forward in Phonics and Word Study</em> published by Scholastic and the Pioneer Valley Books Bella and Rosie series, along with various fiction and nonfiction books used worldwide by teachers. Dedicated to advancing literacy education, Michèle strives to elevate children's reading journeys while providing valuable support to educators globally."

# Social
social:
  instagram: https://www.instagram.com/pvalleybooks/
  facebook: https://www.facebook.com/pioneervalleybooks
  twitter: https://twitter.com/pvalleybooks
  youtube: https://www.youtube.com/user/pioneervalleybooks

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
