title: "Let's Read with the Digital Reader"
email: sarahc@pvep.com
description: The Literacy Tool That Fits Every Classroom
image: 'assets/images/about.png'
timezone: UTC
baseurl: "/digital-reader-blog"
permalink: "/:title/"
logo: 'assets/images/lets-read-dr.png'
icon: 'assets/images/digital-reader.svg'
favicon: 'assets/images/favicon.png'
author:
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: 'assets/images/about.png'

# Authors
authors:
  Michèle Dufresne:
    name: Michèle Dufresne
    display_name: Michèle Dufresne
    avatar: 'assets/images/michele.png'
    email: contactus@pioneervalleybooks.com
    web: https://www.digitalreader.com/
    twitter: https://twitter.com/pvalleybooks
    description: "Michèle Dufresne is a former literacy specialist who has has transformed her dedication to teaching children how to read into a focal point of her writing, speaking, and teaching endeavors. She's a best-selling author known for the Bella and Rosie series, along with various fiction and nonfiction books used worldwide by teachers. Holding a doctorate from the University of Massachusetts, Michèle has been a classroom teacher, language arts specialist, and consultant. Her accolades include the 2017 Moonbeam Children’s Silver Book Award for "Oki and the Polar Bear." Dedicated to advancing literacy education, Michèle strives to elevate children's reading journeys while providing valuable support to educators globally."

# Social
social:
  instagram: https://www.instagram.com/pvalleybooks/
  facebook: https://www.facebook.com/pioneervalleybooks
  twitter: https://twitter.com/pvalleybooks
  youtube: https://www.youtube.com/user/pioneervalleybooks

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
